language: python

python:
  - "3.5"

install:
  - bash ./.create-env-miniconda.sh
  - source ./.activate.sh

script:
  - python -m pytest -v --cov=pyshapes tests/
  - # py.test -v --cov=pyshapes tests/

after_success:
  - coveralls
